# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(685, 528)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 661, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.tabCriterion = QtWidgets.QWidget()
        self.tabCriterion.setObjectName("tabCriterion")
        self.groupBoxFirstCriterion = QtWidgets.QGroupBox(self.tabCriterion)
        self.groupBoxFirstCriterion.setGeometry(QtCore.QRect(0, 10, 321, 291))
        self.groupBoxFirstCriterion.setObjectName("groupBoxFirstCriterion")
        self.widget = QtWidgets.QWidget(self.groupBoxFirstCriterion)
        self.widget.setGeometry(QtCore.QRect(0, 24, 320, 261))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(283, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayoutFirstCriterion = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFirstCriterion.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayoutFirstCriterion.setObjectName("horizontalLayoutFirstCriterion")
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutFirstCriterion.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelFirstCrietrion = QtWidgets.QLabel(self.widget)
        self.labelFirstCrietrion.setObjectName("labelFirstCrietrion")
        self.verticalLayout.addWidget(self.labelFirstCrietrion)
        self.comboBoxFirstCriterion = QtWidgets.QComboBox(self.widget)
        self.comboBoxFirstCriterion.setObjectName("comboBoxFirstCriterion")
        self.verticalLayout.addWidget(self.comboBoxFirstCriterion)
        self.horizontalLayoutFirstCriterion.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutFirstCriterion.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayoutFirstCriterion)
        self.horizontalLayoutMinimumFirstCriterion = QtWidgets.QHBoxLayout()
        self.horizontalLayoutMinimumFirstCriterion.setObjectName("horizontalLayoutMinimumFirstCriterion")
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutMinimumFirstCriterion.addItem(spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelMinimumFirstCriterion = QtWidgets.QLabel(self.widget)
        self.labelMinimumFirstCriterion.setMinimumSize(QtCore.QSize(100, 20))
        self.labelMinimumFirstCriterion.setObjectName("labelMinimumFirstCriterion")
        self.horizontalLayout_2.addWidget(self.labelMinimumFirstCriterion)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.labelMinimumValueFirstCriterion = QtWidgets.QLabel(self.widget)
        self.labelMinimumValueFirstCriterion.setMinimumSize(QtCore.QSize(60, 20))
        self.labelMinimumValueFirstCriterion.setText("")
        self.labelMinimumValueFirstCriterion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMinimumValueFirstCriterion.setObjectName("labelMinimumValueFirstCriterion")
        self.horizontalLayout_2.addWidget(self.labelMinimumValueFirstCriterion)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.sliderMinimumFirstCriterion = QtWidgets.QSlider(self.widget)
        self.sliderMinimumFirstCriterion.setEnabled(True)
        self.sliderMinimumFirstCriterion.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMinimumFirstCriterion.setObjectName("sliderMinimumFirstCriterion")
        self.verticalLayout_2.addWidget(self.sliderMinimumFirstCriterion)
        self.horizontalLayoutMinimumFirstCriterion.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutMinimumFirstCriterion.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayoutMinimumFirstCriterion)
        self.horizontalLayoutMaximumFirstCriterion = QtWidgets.QHBoxLayout()
        self.horizontalLayoutMaximumFirstCriterion.setObjectName("horizontalLayoutMaximumFirstCriterion")
        spacerItem6 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutMaximumFirstCriterion.addItem(spacerItem6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelMaximumFirstCriterion = QtWidgets.QLabel(self.widget)
        self.labelMaximumFirstCriterion.setMinimumSize(QtCore.QSize(100, 20))
        self.labelMaximumFirstCriterion.setObjectName("labelMaximumFirstCriterion")
        self.horizontalLayout_4.addWidget(self.labelMaximumFirstCriterion)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.labelMaximumValueFirstCriterion = QtWidgets.QLabel(self.widget)
        self.labelMaximumValueFirstCriterion.setMinimumSize(QtCore.QSize(60, 20))
        self.labelMaximumValueFirstCriterion.setText("")
        self.labelMaximumValueFirstCriterion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMaximumValueFirstCriterion.setObjectName("labelMaximumValueFirstCriterion")
        self.horizontalLayout_4.addWidget(self.labelMaximumValueFirstCriterion)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.sliderMaximumFirstCriterion = QtWidgets.QSlider(self.widget)
        self.sliderMaximumFirstCriterion.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMaximumFirstCriterion.setObjectName("sliderMaximumFirstCriterion")
        self.verticalLayout_3.addWidget(self.sliderMaximumFirstCriterion)
        self.horizontalLayoutMaximumFirstCriterion.addLayout(self.verticalLayout_3)
        spacerItem8 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutMaximumFirstCriterion.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayoutMaximumFirstCriterion)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButtonAscendingOrder = QtWidgets.QRadioButton(self.widget)
        self.radioButtonAscendingOrder.setObjectName("radioButtonAscendingOrder")
        self.horizontalLayout.addWidget(self.radioButtonAscendingOrder)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.radioButtonDescendingOrder = QtWidgets.QRadioButton(self.widget)
        self.radioButtonDescendingOrder.setObjectName("radioButtonDescendingOrder")
        self.horizontalLayout.addWidget(self.radioButtonDescendingOrder)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem10 = QtWidgets.QSpacerItem(283, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.pushButtonDone = QtWidgets.QPushButton(self.tabCriterion)
        self.pushButtonDone.setGeometry(QtCore.QRect(70, 320, 113, 32))
        self.pushButtonDone.setObjectName("pushButtonDone")
        self.tabWidget.addTab(self.tabCriterion, "")
        self.tabTableResult = QtWidgets.QWidget()
        self.tabTableResult.setObjectName("tabTableResult")
        self.tableResult = QtWidgets.QTableView(self.tabTableResult)
        self.tableResult.setGeometry(QtCore.QRect(10, 10, 631, 351))
        self.tableResult.setObjectName("tableResult")
        self.tabWidget.addTab(self.tabTableResult, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 685, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBoxFirstCriterion.setTitle(_translate("MainWindow", "1st Criterion"))
        self.labelFirstCrietrion.setText(_translate("MainWindow", "Select the first criterion"))
        self.labelMinimumFirstCriterion.setText(_translate("MainWindow", "Minimum Value"))
        self.labelMaximumFirstCriterion.setText(_translate("MainWindow", "Maximum Value"))
        self.radioButtonAscendingOrder.setText(_translate("MainWindow", "Ascending Order"))
        self.radioButtonDescendingOrder.setText(_translate("MainWindow", "Descending Order"))
        self.pushButtonDone.setText(_translate("MainWindow", "Done"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCriterion), _translate("MainWindow", "Criterion"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTableResult), _translate("MainWindow", "Tabled Result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

