# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 528)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 10, 941, 471))
        self.widget.setObjectName("widget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabCriterion = QtWidgets.QWidget()
        self.tabCriterion.setObjectName("tabCriterion")
        self.pushButtonDone = QtWidgets.QPushButton(self.tabCriterion)
        self.pushButtonDone.setGeometry(QtCore.QRect(360, 400, 113, 32))
        self.pushButtonDone.setObjectName("pushButtonDone")
        self.widget1 = QtWidgets.QWidget(self.tabCriterion)
        self.widget1.setGeometry(QtCore.QRect(1, 10, 911, 381))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.groupBoxFirstCriterion = QtWidgets.QGroupBox(self.widget1)
        self.groupBoxFirstCriterion.setMinimumSize(QtCore.QSize(350, 0))
        self.groupBoxFirstCriterion.setObjectName("groupBoxFirstCriterion")
        self.widget2 = QtWidgets.QWidget(self.groupBoxFirstCriterion)
        self.widget2.setGeometry(QtCore.QRect(0, 25, 327, 344))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(283, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayoutFirstCriterion = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFirstCriterion.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayoutFirstCriterion.setObjectName("horizontalLayoutFirstCriterion")
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutFirstCriterion.addItem(spacerItem3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelFirstCrietrion = QtWidgets.QLabel(self.widget2)
        self.labelFirstCrietrion.setObjectName("labelFirstCrietrion")
        self.verticalLayout.addWidget(self.labelFirstCrietrion)
        self.comboBoxFirstCriterion = QtWidgets.QComboBox(self.widget2)
        self.comboBoxFirstCriterion.setObjectName("comboBoxFirstCriterion")
        self.verticalLayout.addWidget(self.comboBoxFirstCriterion)
        self.horizontalLayoutFirstCriterion.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutFirstCriterion.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayoutFirstCriterion)
        self.horizontalLayoutMinimumFirstCriterion = QtWidgets.QHBoxLayout()
        self.horizontalLayoutMinimumFirstCriterion.setObjectName("horizontalLayoutMinimumFirstCriterion")
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutMinimumFirstCriterion.addItem(spacerItem5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelMinimumFirstCriterion = QtWidgets.QLabel(self.widget2)
        self.labelMinimumFirstCriterion.setMinimumSize(QtCore.QSize(100, 20))
        self.labelMinimumFirstCriterion.setObjectName("labelMinimumFirstCriterion")
        self.horizontalLayout_2.addWidget(self.labelMinimumFirstCriterion)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.labelMinimumValueFirstCriterion = QtWidgets.QLabel(self.widget2)
        self.labelMinimumValueFirstCriterion.setMinimumSize(QtCore.QSize(60, 20))
        self.labelMinimumValueFirstCriterion.setText("")
        self.labelMinimumValueFirstCriterion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMinimumValueFirstCriterion.setObjectName("labelMinimumValueFirstCriterion")
        self.horizontalLayout_2.addWidget(self.labelMinimumValueFirstCriterion)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.sliderMinimumFirstCriterion = QtWidgets.QSlider(self.widget2)
        self.sliderMinimumFirstCriterion.setEnabled(True)
        self.sliderMinimumFirstCriterion.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMinimumFirstCriterion.setObjectName("sliderMinimumFirstCriterion")
        self.verticalLayout_2.addWidget(self.sliderMinimumFirstCriterion)
        self.horizontalLayoutMinimumFirstCriterion.addLayout(self.verticalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutMinimumFirstCriterion.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayoutMinimumFirstCriterion)
        self.horizontalLayoutMaximumFirstCriterion = QtWidgets.QHBoxLayout()
        self.horizontalLayoutMaximumFirstCriterion.setObjectName("horizontalLayoutMaximumFirstCriterion")
        spacerItem8 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutMaximumFirstCriterion.addItem(spacerItem8)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelMaximumFirstCriterion = QtWidgets.QLabel(self.widget2)
        self.labelMaximumFirstCriterion.setMinimumSize(QtCore.QSize(100, 20))
        self.labelMaximumFirstCriterion.setObjectName("labelMaximumFirstCriterion")
        self.horizontalLayout_4.addWidget(self.labelMaximumFirstCriterion)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.labelMaximumValueFirstCriterion = QtWidgets.QLabel(self.widget2)
        self.labelMaximumValueFirstCriterion.setMinimumSize(QtCore.QSize(60, 20))
        self.labelMaximumValueFirstCriterion.setText("")
        self.labelMaximumValueFirstCriterion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMaximumValueFirstCriterion.setObjectName("labelMaximumValueFirstCriterion")
        self.horizontalLayout_4.addWidget(self.labelMaximumValueFirstCriterion)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.sliderMaximumFirstCriterion = QtWidgets.QSlider(self.widget2)
        self.sliderMaximumFirstCriterion.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMaximumFirstCriterion.setObjectName("sliderMaximumFirstCriterion")
        self.verticalLayout_3.addWidget(self.sliderMaximumFirstCriterion)
        self.horizontalLayoutMaximumFirstCriterion.addLayout(self.verticalLayout_3)
        spacerItem10 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutMaximumFirstCriterion.addItem(spacerItem10)
        self.verticalLayout_4.addLayout(self.horizontalLayoutMaximumFirstCriterion)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem11 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.labelFirstCirterionIdealValue = QtWidgets.QLabel(self.widget2)
        self.labelFirstCirterionIdealValue.setObjectName("labelFirstCirterionIdealValue")
        self.horizontalLayout_3.addWidget(self.labelFirstCirterionIdealValue)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.lineFirstCriterionIdealValue = QtWidgets.QLineEdit(self.widget2)
        self.lineFirstCriterionIdealValue.setObjectName("lineFirstCriterionIdealValue")
        self.horizontalLayout_3.addWidget(self.lineFirstCriterionIdealValue)
        spacerItem13 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem14 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.labelFirstCriterionWeight = QtWidgets.QLabel(self.widget2)
        self.labelFirstCriterionWeight.setObjectName("labelFirstCriterionWeight")
        self.horizontalLayout_5.addWidget(self.labelFirstCriterionWeight)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.spinBoxFirstCriterionWeight = QtWidgets.QSpinBox(self.widget2)
        self.spinBoxFirstCriterionWeight.setObjectName("spinBoxFirstCriterionWeight")
        self.horizontalLayout_5.addWidget(self.spinBoxFirstCriterionWeight)
        spacerItem16 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem16)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButtonFirstCriterionAscendingOrder = QtWidgets.QRadioButton(self.widget2)
        self.radioButtonFirstCriterionAscendingOrder.setObjectName("radioButtonFirstCriterionAscendingOrder")
        self.horizontalLayout.addWidget(self.radioButtonFirstCriterionAscendingOrder)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem17)
        self.radioButtonFirstCriterionDescendingOrder = QtWidgets.QRadioButton(self.widget2)
        self.radioButtonFirstCriterionDescendingOrder.setObjectName("radioButtonFirstCriterionDescendingOrder")
        self.horizontalLayout.addWidget(self.radioButtonFirstCriterionDescendingOrder)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem18 = QtWidgets.QSpacerItem(283, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem18)
        self.horizontalLayout_11.addWidget(self.groupBoxFirstCriterion)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem19)
        self.groupBoxSecondCriterion = QtWidgets.QGroupBox(self.widget1)
        self.groupBoxSecondCriterion.setMinimumSize(QtCore.QSize(350, 0))
        self.groupBoxSecondCriterion.setObjectName("groupBoxSecondCriterion")
        self.layoutWidget = QtWidgets.QWidget(self.groupBoxSecondCriterion)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 25, 327, 344))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem20 = QtWidgets.QSpacerItem(283, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem20)
        self.horizontalLayoutSecondCriterion = QtWidgets.QHBoxLayout()
        self.horizontalLayoutSecondCriterion.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayoutSecondCriterion.setObjectName("horizontalLayoutSecondCriterion")
        spacerItem21 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutSecondCriterion.addItem(spacerItem21)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelSecondCrietrion = QtWidgets.QLabel(self.layoutWidget)
        self.labelSecondCrietrion.setObjectName("labelSecondCrietrion")
        self.verticalLayout_6.addWidget(self.labelSecondCrietrion)
        self.comboBoxSecondCriterion = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxSecondCriterion.setObjectName("comboBoxSecondCriterion")
        self.verticalLayout_6.addWidget(self.comboBoxSecondCriterion)
        self.horizontalLayoutSecondCriterion.addLayout(self.verticalLayout_6)
        spacerItem22 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutSecondCriterion.addItem(spacerItem22)
        self.verticalLayout_5.addLayout(self.horizontalLayoutSecondCriterion)
        self.horizontalLayoutMinimumSecondCriterion = QtWidgets.QHBoxLayout()
        self.horizontalLayoutMinimumSecondCriterion.setObjectName("horizontalLayoutMinimumSecondCriterion")
        spacerItem23 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutMinimumSecondCriterion.addItem(spacerItem23)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelMinimumSecondCriterion = QtWidgets.QLabel(self.layoutWidget)
        self.labelMinimumSecondCriterion.setMinimumSize(QtCore.QSize(100, 20))
        self.labelMinimumSecondCriterion.setObjectName("labelMinimumSecondCriterion")
        self.horizontalLayout_6.addWidget(self.labelMinimumSecondCriterion)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem24)
        self.labelMinimumValueSecondCriterion = QtWidgets.QLabel(self.layoutWidget)
        self.labelMinimumValueSecondCriterion.setMinimumSize(QtCore.QSize(60, 20))
        self.labelMinimumValueSecondCriterion.setText("")
        self.labelMinimumValueSecondCriterion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMinimumValueSecondCriterion.setObjectName("labelMinimumValueSecondCriterion")
        self.horizontalLayout_6.addWidget(self.labelMinimumValueSecondCriterion)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.sliderMinimumSecondCriterion = QtWidgets.QSlider(self.layoutWidget)
        self.sliderMinimumSecondCriterion.setEnabled(True)
        self.sliderMinimumSecondCriterion.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMinimumSecondCriterion.setObjectName("sliderMinimumSecondCriterion")
        self.verticalLayout_7.addWidget(self.sliderMinimumSecondCriterion)
        self.horizontalLayoutMinimumSecondCriterion.addLayout(self.verticalLayout_7)
        spacerItem25 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutMinimumSecondCriterion.addItem(spacerItem25)
        self.verticalLayout_5.addLayout(self.horizontalLayoutMinimumSecondCriterion)
        self.horizontalLayoutMaximumSecondCriterion = QtWidgets.QHBoxLayout()
        self.horizontalLayoutMaximumSecondCriterion.setObjectName("horizontalLayoutMaximumSecondCriterion")
        spacerItem26 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutMaximumSecondCriterion.addItem(spacerItem26)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelMaximumSecondCriterion = QtWidgets.QLabel(self.layoutWidget)
        self.labelMaximumSecondCriterion.setMinimumSize(QtCore.QSize(100, 20))
        self.labelMaximumSecondCriterion.setObjectName("labelMaximumSecondCriterion")
        self.horizontalLayout_7.addWidget(self.labelMaximumSecondCriterion)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem27)
        self.labelMaximumValueSecondCriterion = QtWidgets.QLabel(self.layoutWidget)
        self.labelMaximumValueSecondCriterion.setMinimumSize(QtCore.QSize(60, 20))
        self.labelMaximumValueSecondCriterion.setText("")
        self.labelMaximumValueSecondCriterion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMaximumValueSecondCriterion.setObjectName("labelMaximumValueSecondCriterion")
        self.horizontalLayout_7.addWidget(self.labelMaximumValueSecondCriterion)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.sliderMaximumSecondCriterion = QtWidgets.QSlider(self.layoutWidget)
        self.sliderMaximumSecondCriterion.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMaximumSecondCriterion.setObjectName("sliderMaximumSecondCriterion")
        self.verticalLayout_8.addWidget(self.sliderMaximumSecondCriterion)
        self.horizontalLayoutMaximumSecondCriterion.addLayout(self.verticalLayout_8)
        spacerItem28 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutMaximumSecondCriterion.addItem(spacerItem28)
        self.verticalLayout_5.addLayout(self.horizontalLayoutMaximumSecondCriterion)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem29 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem29)
        self.labelSecondCirterionIdealValue = QtWidgets.QLabel(self.layoutWidget)
        self.labelSecondCirterionIdealValue.setObjectName("labelSecondCirterionIdealValue")
        self.horizontalLayout_8.addWidget(self.labelSecondCirterionIdealValue)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem30)
        self.lineSecondCriterionIdealValue = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineSecondCriterionIdealValue.setObjectName("lineSecondCriterionIdealValue")
        self.horizontalLayout_8.addWidget(self.lineSecondCriterionIdealValue)
        spacerItem31 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem31)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem32 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem32)
        self.labelSecondCriterionWeight = QtWidgets.QLabel(self.layoutWidget)
        self.labelSecondCriterionWeight.setObjectName("labelSecondCriterionWeight")
        self.horizontalLayout_9.addWidget(self.labelSecondCriterionWeight)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem33)
        self.spinBoxSecondCriterionWeight = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxSecondCriterionWeight.setObjectName("spinBoxSecondCriterionWeight")
        self.horizontalLayout_9.addWidget(self.spinBoxSecondCriterionWeight)
        spacerItem34 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem34)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.radioButtonSecondCriterionAscendingOrder = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButtonSecondCriterionAscendingOrder.setObjectName("radioButtonSecondCriterionAscendingOrder")
        self.horizontalLayout_10.addWidget(self.radioButtonSecondCriterionAscendingOrder)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem35)
        self.radioButtonSecondCriterionDescendingOrder = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButtonSecondCriterionDescendingOrder.setObjectName("radioButtonSecondCriterionDescendingOrder")
        self.horizontalLayout_10.addWidget(self.radioButtonSecondCriterionDescendingOrder)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        spacerItem36 = QtWidgets.QSpacerItem(283, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem36)
        self.horizontalLayout_11.addWidget(self.groupBoxSecondCriterion)
        spacerItem37 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem37)
        self.tabWidget.addTab(self.tabCriterion, "")
        self.tabTableResult = QtWidgets.QWidget()
        self.tabTableResult.setObjectName("tabTableResult")
        self.tableResult = QtWidgets.QTableView(self.tabTableResult)
        self.tableResult.setGeometry(QtCore.QRect(10, 10, 901, 431))
        self.tableResult.setObjectName("tableResult")
        self.tabWidget.addTab(self.tabTableResult, "")
        self.horizontalLayout_12.addWidget(self.tabWidget)
        spacerItem38 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem38)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 945, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonDone.setText(_translate("MainWindow", "Done"))
        self.groupBoxFirstCriterion.setTitle(_translate("MainWindow", "1st Criterion"))
        self.labelFirstCrietrion.setText(_translate("MainWindow", "Select the first criterion"))
        self.labelMinimumFirstCriterion.setText(_translate("MainWindow", "Minimum Value"))
        self.labelMaximumFirstCriterion.setText(_translate("MainWindow", "Maximum Value"))
        self.labelFirstCirterionIdealValue.setText(_translate("MainWindow", "Ideal Value"))
        self.labelFirstCriterionWeight.setText(_translate("MainWindow", "Weight"))
        self.radioButtonFirstCriterionAscendingOrder.setText(_translate("MainWindow", "Ascending Order"))
        self.radioButtonFirstCriterionDescendingOrder.setText(_translate("MainWindow", "Descending Order"))
        self.groupBoxSecondCriterion.setTitle(_translate("MainWindow", "2nd Criterion"))
        self.labelSecondCrietrion.setText(_translate("MainWindow", "Select the second criterion"))
        self.labelMinimumSecondCriterion.setText(_translate("MainWindow", "Minimum Value"))
        self.labelMaximumSecondCriterion.setText(_translate("MainWindow", "Maximum Value"))
        self.labelSecondCirterionIdealValue.setText(_translate("MainWindow", "Ideal Value"))
        self.labelSecondCriterionWeight.setText(_translate("MainWindow", "Weight"))
        self.radioButtonSecondCriterionAscendingOrder.setText(_translate("MainWindow", "Ascending Order"))
        self.radioButtonSecondCriterionDescendingOrder.setText(_translate("MainWindow", "Descending Order"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCriterion), _translate("MainWindow", "Criterion"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTableResult), _translate("MainWindow", "Tabled Result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

